[package]
name = "garbage_codes"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "check_boxed_traits"
path = "src/bin/check_boxed_traits.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
